/*
Each new term in the Fibonacci sequence is generated by adding the previous 
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms. 
 */

int Fib(int n)
{
    if (n <= 1) return n;
    else
    {
        return Fib(n - 1) + Fib(n - 2);
    }
}

/*
Console.Write("Input the desired number in the fibonacci sequence: ");
int input = Convert.ToInt32(Console.ReadLine());
Console.WriteLine(Fib(input));
*/

int sum = 0;
for (int i = 2; Fib(i) <= 4_000_000; i++)
{
    Fib(i);
    if (Fib(i) % 2 == 0) sum += Fib(i);
}

Console.WriteLine("Sum of even values <= 4,000,000: " + sum);
